---
title: "NBA Analysis"
author: "Aidan Judge"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(out.width = "100%")
knitr::opts_chunk$set(dpi = 300)

library(readr)
library(ggplot2)
library(dplyr)
library(ggmap)
library(viridis)
library(forcats)
library(smodels, lib.loc = "C:/Program Files/R/R-3.4.0/library")
```

AVAILABLE DATASETS (choose one and delete the others)

```{r}
nfl <- read_csv("https://statsmaths.github.io/stat_data/nfl2015.csv")
taxi <- read_csv("https://statsmaths.github.io/stat_data/nyc_taxi_50.csv")
nba_shots <- read_csv("https://statsmaths.github.io/stat_data/nba_shots.csv")
cancer <- read_csv("https://statsmaths.github.io/stat_data/cancer_inc_data.csv")
```

##Model 1 Relationship between average defender distance on margin of victory/loss

```{r}
individualgames <- group_summarize(nba_shots, matchup)
qplot(close_def_dist_mean, final_margin_mean, data = individualgames) +
  geom_smooth(method = "lm")
```

##Model 2 - Same as Model 1, but is it more significant for closer games (decided by 5 or less)

```{r}
closegames <- filter(individualgames, final_margin_mean >= -10, final_margin_mean <= 10)
qplot(close_def_dist_mean, final_margin_mean, data = closegames) +
  geom_smooth(method = "lm")
```

##Model 4 Group summarize on top 30 players
```{r}
top30players <- group_summarize(nba_shots, fct_lump(player_name, 30))
qplot()
```


